### PR TITLE
Prevent `SelfClosingSVGElements` document filter from erroneously self-closing tags

### LINKED ISSUE #512: `SelfClosingSVGElements` document filter erroneously self-closes `g` tags
As reported in a AMP plugin [support forum topic](https://wordpress.org/support/topic/svg-group-tag-is-broken/), given this input HTML:

```html
<svg>
  <g id="ok">
    <path/>
  </g>
</svg>
```

The output is:

```html
<svg>
  <g id="ok"/>
    <path/>
</svg>
```

I was able to prevent this from happening by commenting out `Tag::G` from `SelfClosingSVGElements::SELF_CLOSING_TAGS`:

https://github.com/ampproject/amp-toolbox-php/blob/4cecbc5953823f15c2f9ea22ec3ee947040c1547/src/Dom/Document/Filter/SelfClosingSVGElements.php#L21-L25

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #512

Ensures that `SelfClosingSVGElements` will properly process:

* SVG DOM trees that contain newlines.
* SVG self-closing that have no whitespace (e.g. `<path/>` as opposed to `<path />`).

### CODE REVIEW

File: tests/Dom/DocumentTest.php [hunk 1]
```diff
@@ -1471,6 +1471,22 @@ public function dataSVGSelfClosingElements()
...
+                . '<svg>' . PHP_EOL
+                . '  <g id="ok">' . PHP_EOL
+                . '    <path/>' . PHP_EOL
+                . '  </g>' . PHP_EOL
+                . '</svg>' . PHP_EOL
+                . '</body></html>',
+                '<!DOCTYPE html><html>' . $head . '<body>' . PHP_EOL
+                . '<svg>' . PHP_EOL
+                . '  <g id="ok">' . PHP_EOL
+                . '    <path/>' . PHP_EOL
```
Comment (westonruter) [inline tests/Dom/DocumentTest.php:1486]: This is currently failing in `assertSimilarMarkup`:

```
1) AmpProject\Dom\DocumentTest::testSVGSelfClosingElements with data set "test g tag one path child and newlines" ('<!DOCTYPE html><html><head></.../html>', '<!DOCTYPE html><html><head><m.../html>')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     5 => '<body>'
     6 => '<svg>'
     7 => '<g id="ok">'
-    8 => '<path/>'
+    8 => '<path>'
     9 => '</g>'
     10 => '</svg>'
     11 => '</body>'
     12 => '</html>'
 )
```

Comment (westonruter) [reply tests/Dom/DocumentTest.php]: Addressed in cb091ed07 by using `assertEqualMarkup` instead of `assertSimilarMarkup`.

**Comment by westonruter** [comment]
@schlessera Once this is merged, can a 0.11.0 release be made so we can include it in AMP plugin v2.2.2?

**Review by ediamin — APPROVED** [review]

**Review by schlessera — APPROVED** [review]
